apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-react-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-react
  template:
    metadata:
      labels:
        app: vite-react
    spec:
      containers:
        - name: vite-react-container
          image: gvkvamsy99/vite-react-app:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: service
metadata:
  name: vite-react-service
spec:
  selector:
    app: vite-react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort
